### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by mossan576** [mossan576/chat-space#11]
# IPアドレス
52.197.8.189

**Comment by keisukekodama** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

※今後実装に関する質問がありましたら、メンターに確認をお願いします！

**Comment by mossan576** [comment]
児玉さん！確認ありがとうございます！！
